### ISSUE TITLE
fix CI script

### ISSUE THREAD

**Issue by antongolub** [qiwi/tech-radar#4]
```
      - name: Save artifact
        uses: actions/upload-artifact@v2
        with:
          name: artifact-${{ github.run_id }}
          retention-days: 1
          # need to add any root level file to prevent common dirname part trimming
          path: |
            node_modules
            docs
```
* rm node_modules
* as said in comment add at least one root entry (readme.md for example)
